improve taskfile and change injections from controllers dir to injections dir

diff --git a/Taskfile.yaml b/Taskfile.yaml
--- a/Taskfile.yaml
+++ b/Taskfile.yaml
@@ -6,13 +6,13 @@ vars:
   VALUES_YAML_PATH: "chart/values.yaml"
   GRAPI_INJECTION_FOLDER: "grapi"
   GRUIM_INJECTION_FOLDER: "gruim"
-  BASE: "gras-deploy"
+  BASE: "gras"
   CHART_FOLDER: "./chart"
   CHART_NAME: # use the current folder as the chart name
-    sh: echo ${PWD##*/}
+    sh: if [ "$(echo ${PWD##*/})" != "build" ]; then echo ${PWD##*/}; else echo ${PROJECT_NAME_SHORT}; fi
   CHART_NAME_SHORT: # use the current folder as the chart name
     sh: |
-        string="${PWD##*/}"
+        string="$(if [ "$(echo ${PWD##*/})" != "build" ]; then echo ${PWD##*/}; else echo ${PROJECT_NAME_SHORT}; fi)"
         string="${string//[.\']/}"
         string="${string//[!a-zA-Z ]/ }"
         acronym=''
@@ -177,9 +177,10 @@ tasks:
       - |
         FOLDER={{.GRAPI_INJECTION_FOLDER}}
         BASE64=$(if [[ "$OSTYPE" == "darwin"* ]]; then echo "base64"; else echo "base64 -w 0"; fi)
+        FINDFILES=$(if [[ "$OSTYPE" == "msys"* ]]; then find ${FOLDER} -name '\*.sh' -or -name '\*.bash'; else find ${FOLDER} -name '*.sh' -or -name '*.bash'; fi)
         BASE="{{.BASE}}"  # Ensuring BASE is enclosed in quotes for full path reference
         if yq -e ".${BASE}.${FOLDER}" {{.VALUES_YAML_PATH}} >/dev/null; then
-          for file_path in $(find ${FOLDER} -name "*.sh" -or -name "*.bash"); do  
+          for file_path in $(${FINDFILES}); do
             group_name=$(echo ${file_path} | sed "s,${FOLDER}/,,g" | \
               cut -d/ -f1)
             file_name=$(echo ${file_path} | sed "s,${FOLDER}/,,g" | \
@@ -189,12 +190,15 @@ tasks:
               "s,.${group_name}.${file_extension},,g" | sed \
               "s,.${group_name::${#group_name}-1}.${file_extension},,g" | \
               sed "s,.${file_extension},,g")
-            base64_content=$(cat ${file_path} | ${BASE64})  # Base64 on single line
+            base64_content=$(cat ${file_path} | tr -d '\r' | ${BASE64})  # Base64 on single line
             if [ "${file_name}" = "index.ts" ]; then continue; fi
             echo "patching: ${FOLDER} - ${group_name} - ${injection_name} - \
               ${file_name}"
             yq -i "del(.${BASE}.${FOLDER}.${group_name}[] | \
               select(.name == \"${injection_name}\"))" {{.VALUES_YAML_PATH}}
+            if [ "${group_name}" == "injections" ]; then 
+              group_name = "controllers"
+            fi
             yq -i ".${BASE}.${FOLDER}.${group_name} += [{\"name\": \
               \"${injection_name}\", \"content\": \"${base64_content}\"}]" \
               {{.VALUES_YAML_PATH}}
@@ -203,6 +207,53 @@ tasks:
           echo "failed to add ${FOLDER} values..."
           exit 99
         fi
+
+  reset-values-file:
+    desc: Gather and encode backend (grapi) and frontend (gruim) injections 
+          and update values.yaml
+    cmds:
+      - echo "1) Checking if values.yaml exists..."
+      - |
+        if [ -f "{{.VALUES_YAML_PATH}}" ]; then
+          echo "values.yaml found at {{.VALUES_YAML_PATH}}"
+        else
+          echo "ERROR: values.yaml not found at {{.VALUES_YAML_PATH}}"
+          exit 1
+        fi
+      - echo "2) Resetting grapi injections..."
+      - |
+        FOLDER={{.GRAPI_INJECTION_FOLDER}}
+        BASE64=$(if [[ "$OSTYPE" == "darwin"* ]]; then echo "base64"; else echo "base64 -w 0"; fi)
+        BASE="{{.BASE}}"  # Ensuring BASE is enclosed in quotes for full path reference
+        GROUPS="injections controllers prerelationpatches postpatches"
+        if yq -e ".${BASE}.${FOLDER}" {{.VALUES_YAML_PATH}} >/dev/null; then
+          for group_name in $(echo ${GROUPS}); do
+            echo "reset ${group_name}"
+            yq -i ".${BASE}.${FOLDER}.${group_name} = []" \
+                {{.VALUES_YAML_PATH}}
+          done
+        else
+          echo "failed to reset ${FOLDER} values..."
+          exit 99
+        fi
+ 
+      - echo "3) Resetting gruim injections..."
+      - |
+        FOLDER={{.GRUIM_INJECTION_FOLDER}}
+        BASE64=$(if [[ "$OSTYPE" == "darwin"* ]]; then echo "base64"; else echo "base64 -w 0"; fi)
+        BASE="{{.BASE}}"  # Ensuring BASE is enclosed in quotes for full path reference
+        GROUPS="custommodules"
+        if yq -e ".${BASE}.${FOLDER}" {{.VALUES_YAML_PATH}} >/dev/null; then
+          for group_name in $(echo ${GROUPS}); do
+            echo "reset ${group_name}"
+            yq -i ".${BASE}.${FOLDER}.${group_name} = []" \
+                {{.VALUES_YAML_PATH}}
+          done
+        else
+          echo "failed to reset ${FOLDER} values..."
+          exit 99
+        fi
+      
 
   patch-values-file:
     desc: Gather and encode backend (grapi) and frontend (gruim) injections 
@@ -220,10 +271,12 @@ tasks:
       - |
         FOLDER={{.GRAPI_INJECTION_FOLDER}}
         BASE64=$(if [[ "$OSTYPE" == "darwin"* ]]; then echo "base64"; else echo "base64 -w 0"; fi)
+        SED=$(if [[ "$OSTYPE" == "darwin"* ]]; then echo 'sed -i ".bak"'; else echo "sed -i"; fi)
+        FINDFILES="$(if [[ "$OSTYPE" == "msys"* ]]; then find ${FOLDER} -name '\*.ts' -or -name '\*.sh' -or -name '\*.bash'; else find ${FOLDER} -name '*.ts' -or -name '*.sh' -or -name '*.bash'; fi)"
         BASE="{{.BASE}}"  # Ensuring BASE is enclosed in quotes for full path reference
         if yq -e ".${BASE}.${FOLDER}" {{.VALUES_YAML_PATH}} >/dev/null; then
-          for file_path in $(find ${FOLDER} -name "*.ts" -or \
-            -name "*.sh" -or -name "*.bash"); do  
+          # echo "${FINDFILES}"
+          for file_path in $(echo "${FINDFILES}"); do
             group_name=$(echo ${file_path} | sed "s,${FOLDER}/,,g" | \
               cut -d/ -f1)
             file_name=$(echo ${file_path} | sed "s,${FOLDER}/,,g" | \
@@ -233,16 +286,24 @@ tasks:
               "s,.${group_name}.${file_extension},,g" | sed \
               "s,.${group_name::${#group_name}-1}.${file_extension},,g" | \
               sed "s,.${file_extension},,g")
-            base64_content=$(cat ${file_path} | ${BASE64})  # Base64 on single line
+            if [ "${group_name}" = "injections" ]; then 
+              group_name="controllers"
+              injection_name=$(echo ${injection_name} | sed "s,.controller,,g")
+            fi
+            base64_content=$(cat ${file_path} | tr -d '\r' | ${BASE64})  # Base64 on single line
+            base64_content_file=./tmpfile
+            cat ${file_path} | tr -d '\r' | ${BASE64} > ${base64_content_file}
+            ${SED} "1s/^/content=/" ${base64_content_file}
+            ${SED} "1s/^/name=${injection_name}\n/" ${base64_content_file}
             if [ "${file_name}" = "index.ts" ]; then continue; fi
             echo "patching: ${FOLDER} - ${group_name} - ${injection_name} - \
               ${file_name}"
             yq -i "del(.${BASE}.${FOLDER}.${group_name}[] | \
               select(.name == \"${injection_name}\"))" {{.VALUES_YAML_PATH}}
-            yq -i ".${BASE}.${FOLDER}.${group_name} += [{\"name\": \
-              \"${injection_name}\", \"content\": \"${base64_content}\"}]" \
+            yq -i ".${BASE}.${FOLDER}.${group_name} += [load_props(\"${base64_content_file}\")]" \
               {{.VALUES_YAML_PATH}}
           done
+          rm ${base64_content_file}
         else
           echo "failed to add ${FOLDER} values..."
           exit 99
@@ -252,11 +313,14 @@ tasks:
       - |
         FOLDER={{.GRUIM_INJECTION_FOLDER}}
         BASE64=$(if [[ "$OSTYPE" == "darwin"* ]]; then echo "base64"; else echo "base64 -w 0"; fi)
+        SED=$(if [[ "$OSTYPE" == "darwin"* ]]; then echo 'sed -i ".bak"'; else echo "sed -i"; fi)
+        FINDFILES="$(if [[ "$OSTYPE" == "msys"* ]]; then find ${FOLDER}/${cm} -name '\*.svelte' -or -name '\*.jsx'; else find ${FOLDER}/${cm} -name '*.svelte' -or -name '*.jsx'; fi)
         BASE="{{.BASE}}"  # Ensuring BASE is enclosed in quotes for full path reference
         cm="custommodules"
         if yq -e ".${BASE}.${FOLDER}" {{.VALUES_YAML_PATH}} >/dev/null; then
           yq -i "del(.${BASE}.${FOLDER}.${cm}[])" {{.VALUES_YAML_PATH}}
-          for file_path in $(find ${FOLDER}/${cm} -name "*.jsx"); do 
+          # echo "${FINDFILES}"
+          for file_path in $(echo "${FINDFILES}"); do
             group_name=$(echo ${file_path} | sed "s,${FOLDER}/,,g" | \
               cut -d/ -f1)
             file_name=$(echo ${file_path} | sed "s,${FOLDER}/,,g" | \
@@ -267,14 +331,18 @@ tasks:
               "s,.${group_name::${#group_name}-1}.${file_extension},,g" | \
               sed "s,.${file_extension},,g")
             injection_name=$(echo ${file_name} | sed "s,.${file_extension},,g")
-            base64_content=$(cat ${file_path} | ${BASE64})  # Base64 on single line
+            base64_content=$(cat ${file_path} | tr -d '\r' | ${BASE64})  # Base64 on single line
+            base64_content_file=./tmpfile
+            cat ${file_path} | tr -d '\r' | ${BASE64} > ${base64_content_file}
+            ${SED} "1s/^/content=/" ${base64_content_file}
+            ${SED} "1s/^/name=${injection_name}\n/" ${base64_content_file}
             if [ "${file_name}" = "index.ts" ]; then continue; fi
             echo "patching: ${FOLDER} - ${cm} - ${injection_name} - \
               ${file_name}"
-            yq -i ".${BASE}.${FOLDER}.${cm} += [{\"name\": \
-              \"${injection_name}\", \"content\": \"${base64_content}\"}]" \
+            yq -i ".${BASE}.${FOLDER}.${cm} += [load_props(\"${base64_content_file}\")]" \
               {{.VALUES_YAML_PATH}}
           done
+          rm ${base64_content_file}
         else
           echo "failed to add ${FOLDER} values..."
           exit 99
@@ -365,7 +433,23 @@ tasks:
         yq e -i '.image.repository = "{{.IMAGE_REGISTRY}}/{{.IMAGE_REPO}}"' {{.VALUES_YAML_PATH}}
         yq e -i '.image.tag = "{{.TAG}}"' {{.VALUES_YAML_PATH}}
 
-        helm upgrade --install {{.CHART_NAME}} {{.AWS_REPO_URL}}/{{.CHART_NAME}} --version {{.SEMVER}} --namespace {{.NS}} --create-namespace
+        VALUES_STAGE=$(echo "{{.VALUES_YAML_PATH}}" | sed "s,.yaml,-{{.STAGE}}.yaml,g")
+        echo "VALUES_STAGE: ${VALUES_STAGE}"
+        if [ -f ${VALUES_STAGE} ]; then
+
+          # patch data container:
+          yq e -i '.gras.grapi.initContainers[0].spec.image = "grpl/jcs-{{.STAGE}}-data:{{.TAG}}"' ${VALUES_STAGE} || true
+          yq e -i '.gras.grapi.initContainers[1].spec.image = "grpl/jcs-{{.STAGE}}-data:{{.TAG}}"' ${VALUES_STAGE} || true
+
+          VALUES_FILE_COMMAND=" --values ${VALUES_STAGE} "
+          echo "VALUES_FILE_STAGE: ${VALUES_FILE_STAGE}"
+
+        else
+          VALUES_FILE_STAGE=""
+        fi
+
+
+        helm upgrade --install {{.CHART_NAME}} {{.AWS_REPO_URL}}/{{.CHART_NAME}} ${VALUES_FILE_COMMAND} --version {{.SEMVER}} --namespace {{.NS}} --create-namespace
 
   deploy-local:
     desc: Deploy the Helm chart to the Grapple cluster
@@ -388,6 +472,37 @@ tasks:
         helm dep up chart
 
         helm upgrade --install {{.CHART_NAME}} {{.CHART_FOLDER}} --namespace "{{.CHART_NAME_SHORT}}-{{.STAGE}}-{{.GIT_HASH}}" --create-namespace
+
+  update-bitbucket-pr:
+    desc: Deploy the Helm chart to the Grapple cluster
+    cmds:
+      - |
+        echo "wait on grapi deployments"
+        echo "kubectl get grapi -n {{.NS}}"
+        kubectl get grapi -n {{.NS}}
+        sleep 10
+        echo "kubectl wait grapi -n {{.NS}} -l app.kubernetes.io/component=grapi --for condition=Synced"
+        kubectl wait grapi -n {{.NS}} -l app.kubernetes.io/component=grapi --for condition=Synced
+        kubectl wait gruim -n {{.NS}} -l app.kubernetes.io/component=gruim --for condition=Synced
+        sleep 3
+        APPURL=$(kubectl get ing -n {{.NS}} -l app.kubernetes.io/layer=app -o jsonpath="{.items[0].spec.rules[0].host}")
+        echo "APPURL: ${APPURL}"
+        GRUIMURL=$(kubectl get ing -n {{.NS}} -l app.kubernetes.io/name=gruim -o jsonpath="{.items[0].spec.rules[0].host}")
+        echo "GRUIMURL: ${GRUIMURL}"
+        GRAPIURL=$(kubectl get ing -n {{.NS}} -l app.kubernetes.io/name=grapi -o jsonpath="{.items[0].spec.rules[0].host}")
+        echo "GRAPIURL: ${GRAPIURL}"
+        if [ "${BITBUCKET_PR_ID}" != "" ]; then
+          curl https://api.bitbucket.org/2.0/repositories/wolke7-patrick/jcs/pullrequests/${BITBUCKET_PR_ID}/comments \
+            -u ${bbuser}:${bbpw} \
+            --request POST \
+            --header 'Content-Type: application/json' \
+            --data "{
+            \"content\": {
+                \"raw\": \"TestURL (app): [http://${APPURL}](http://${APPURL}) -- Frontend (gruim): [http://${GRUIMURL}](http://${GRUIMURL}) -- Backend (grapi): [http://${GRAPIURL}](http://${GRAPIURL})\"
+            }
+            }"
+        fi
+
 
   build-and-deploy-local:
     desc: Build, package, and push the Helm chart in one step
